spring:
  cloud: 
    config: 
      uri: http://config-example:8888
      server: 
        git:
          uri: https://github.ibm.com/yuziyang/config-repo.git
          default-label: master
          # username: 870724731@qq.com
          # password: yzy199761
        # native: 
        #   searchLocations: classpath:/conf


